apiVersion: v2
name: test-dexlektika
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: 11.6.17
    repository: https://charts.bitnami.com/bitnami
